#
# example of configuration file
#

[general]
trayicon = true             # enable or disable tray icon
genloop = true              # enable or disable RSS generation loop (if set to 'false' then generation will be triggered only once)
startupdelay = 0            # set delay in seconds before first generation (useful on startup to wait for KeePassXC to start before) 
startserver = true          # set 'false' to prevent starting RSS server (just store data to local files), default: true
port = 8080                 # RSS feed port, default 8080
refreshtime = 3600          # time in seconds between consecutive RSS generator loop iterations, default 3600
dataroot = "data"           # path to store data; path absolute or relative to config directory
                            # default value is app dir inside user home directory
logdir = "log"              # path to store logs; path absolute or relative to config directory
                            # default value is app dir inside user home directory
logviewer = "mousepad %s"   # command line to view log file, %s will be replaced with log path

[[item]]
generator = "librus"
enabled = true                      # enable or disable scraper
auth.type = "RAW"                   # authenticate by providing unencrypted user and password
auth.user = "12345678"              # login example (librus id)
auth.pass = "user_secret"           # password example

[[item]]
generator = "earlystage"
enabled = true                                              # enable or disable scraper
auth.type = "KEEPASSXC"                                     # authenticate by accessing keepassxc deamon
auth.itemurl = "https://online.earlystage.pl/logowanie/"    # URL of keepassxc item (proper user/pass is identified by the URL)

[[item]]
generator = "youtube"
enabled = true
params.url = "https://www.youtube.com/@YouTube/videos"      # YT content link
params.itemsperfetch = 20                                   # how many items to fetch during each generation
params.outfile = "the-yt-videos.xml"                        # output subpath with RSS content
