#
# example of configuration file
#

[general]
port = 8080             # RSS feed port
refreshtime = 3600      # time in seconds
dataroot = "data"       # relative path to current working directory (absolute path possible)
                        # default value is app dir inside user home directory

[site.librus]
enabled = true                      # enable or disable scraper
auth.type = "RAW"                   # authenticate by providing unencrypted user and password
auth.user = "user123@librus.com"    # login example
auth.pass = "user_secret"           # password example

[site.earlystage]
enabled = true                                              # enable or disable scraper
auth.type = "KEEPASSXC"                                     # authenticate by accessing keepassxc deamon
auth.itemurl = "https://online.earlystage.pl/logowanie/"    # URL of keepassxc item (proper user/pass is identified by the URL)
